#!/bin/bash
echo "Laraval env installer"
echo "Please wait ..."
echo
#INSTALL DEPENDENCIES
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
apt-get install -y apache2 php git curl unzip php-mbstring php-xml phpunit php-sqlite3 php7.0-mysql mariadb-server libapache2-mod-php yarn
#INSTALL COMPOSER
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '61069fe8c6436a4468d0371454cf38a812e451a14ab1691543f25a9627b97ff96d8753d92a00654c21e2212a5ae1ff36') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar /usr/local/bin/composer
#MySQL
#mysql --user="root" --password="$password" --execute="CREATE DATABASE homestead DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"
#mysql --user="root" --password="$password" --execute="CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret';"
#mysql --user="root" --password="$password" --execute="GRANT ALL PRIVILEGES ON homestead.* TO 'homestead'@'localhost' WITH GRANT OPTION;"
#mysql --user="root" --password="$password" --execute="FLUSH PRIVILEGES;"  
#Apache2
cd /etc/apache2/sites-available
cat > /etc/apache2/sites-available/canvas.conf <<EOF
<VirtualHost *:80>
    ServerName localhost
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html/canvas/public
    <Directory /var/www/html/canvas>
        AllowOverride All
    </Directory>
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
EOF
a2dissite 000-default.conf
a2ensite canvas.conf
a2enmod rewrite
service apache2 restart
#CANVAS
cd /var/www/html
composer create-project --prefer-dist cnvs/canvas canvas
cd canvas 
chgrp -R www-data /var/www/html/canvas
chmod -R 775 /var/www/html/canvas/storage
composer install
yarn
php artisan storage:link
wget https://raw.githubusercontent.com/PastaGringo/scripts/master/.env_canvas
mv .env_canvas .env 
php artisan canvas:install
