#!/bin/bash
clear                                                                                                                                                                          
echo "Hello !"
echo "Welcome to FreshRSS installer for QuickBox!"
echo
PS3='What do you want to do ?: '
options=("Add FreshRSS to QuickBox Package Manager (BOX)" "Remove FreshRSS from QuickBox Package Manager (BOX)" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Add FreshRSS to QuickBox Package Manager (BOX)")
                echo "Copying files..."
                wget https://raw.githubusercontent.com/PastaGringo/scripts/master/installpackage-freshrss -P /usr/local/bin/quickbox/package/install
                wget https://raw.githubusercontent.com/PastaGringo/scripts/master/removepackage-freshrss -P  /usr/local/bin/quickbox/package/remove
                echo "OK!"
                echo "Now, please start BOX with root account and select Fresh to install it!"
                echo "See ya!"
                echo
                break
                ;;
        "Remove FreshRSS from QuickBox Package Manager (BOX)")
                echo "Removing files..."
                echo "OK!"
                echo "See ya!"
                echo
                break
                ;;
        "Quit")
                echo "See ya!"
                echo
                break
            ;;
        *) echo invalid option;;
    esac
done
                                                                                                                                                                               
                          
