#!/bin/bash
echo "Hello !"
echo "Welcome to FreshRSS installer for QuickBox!"
PS3='What do you want to do ?: '
options=("Install FreshRSS to QuickBox Package Manager (BOX)" "Install FreshRSS to QuickBox Package Manager (BOX)" "Option 3" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Option 1")
            echo "you chose choice 1"
            ;;
        "Option 2")
            echo "you chose choice 2"
            ;;
        "Option 3")
            echo "you chose choice 3"
            ;;
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done
