#!/bin/sh
echo
echo "Radarr installer for Quickbox.io"
echo

username=$(cat /srv/rutorrent/home/db/master.txt)
ip=$(curl -s http://whatismyip.akamai.com)

sudo apt update
sudo apt-get install -y libmono-cil-dev curl mediainfo

cd /opt
sudo wget https://github.com/Radarr/Radarr/releases/download/v0.2.0.210/Radarr.develop.0.2.0.210.linux.tar.gz
sudo tar -xvzf /opt/Radarr.develop.0.2.0.210.linux.tar.gz
sudo rm -rf /opt/Radarr.develop.0.2.0.210.linux.tar.gz

sudo cat > /etc/systemd/system/radarr.service <<EOF
[Unit]
Description=Radarr Daemon
After=syslog.target network.target
[Service]
User=${username}
Group=${username}
Type=simple
ExecStart=/usr/bin/mono /opt/Radarr/Radarr.exe -nobrowser
TimeoutStopSec=20
KillMode=process
Restart=on-failure
[Install]
WantedBy=multi-user.target
EOF

sudo cat > /etc/apache2/sites-enabled/radarr.conf <<EOF
<Location /radarr>
ProxyPass http://localhost:7878/radarr
ProxyPassReverse http://localhost:7878/radarr
AuthType Digest
AuthName "rutorrent"
AuthUserFile '/etc/htpasswd'
Require user ${username}
</Location>
EOF

sudo chown -R pastadmin: /opt/Radarr/
sudo chown www-data: /etc/apache2/sites-enabled/radarr.conf

sudo systemctl enable radarr.service

sudo systemctl daemon-reload
sudo systemctl start radarr.service
sleep 10
sudo systemctl stop radarr.service
sudo sed -i "s/<UrlBase>.*/<UrlBase>radarr<\/UrlBase>/g" /home/${username}/.config/Radarr/config.xml
sudo sed -i "s/<BindAddress>.*/<BindAddress>127.0.0.1<\/BindAddress>/g" /home/${username}/.config/Radarr/config.xml
sleep 10
sudo systemctl start radarr.service
echo "Radarr is installed !"
echo "You can access it at  : http://$ip/radarr"
echo "Have fun!"
