#!/bin/bash
echo
echo "Welcome to the Flexget QuickBox installer !"
echo
echo "Before setting up Flexget, I need to know fews things"
echo -n "T411 username: "
read t411usr
echo -n "T411 password: "
read t411pwd
echo -n "Flexget Web UI password?: "
read flexgetwebuipwd
echo "Thanks!"
echo ""
echo "Starting the installation ..."
echo ""
sudo pip install flexget
mkdir ~/.config
mkdir ~/.config/flexget
cat > ~/.config/flexget/config.yml <<EOF
tasks:                                                                                                                                                                         
  feed-720p:                                                                                                                                                             
  disable: seen                                                                                                                                                              
    exists_movie:                                                                                                                                                              
      path: /home/pastadmin/torrents/rtorrent/                                                                                                                                 
      lookup: imdb                                                                                                                                                             
      type: files                                                                                                                                                              
    priority: 2                                                                                                                                                                
    imdb:                                                                                                                                                                      
      min_score: 5                                                                                                                                                             
      min_year: 2016                                                                                                                                                           
    t411:                                                                                                                                                                      
      category: Film                                                                                                                                                           
      terms:                                                                                                                                                                   
        - Français (VFF/Truefrench)                                                                                                                                            
        - Multi (Français inclus)                                                                                                                                              
        - HDrip 720                                                                                                                                                            
        - Web-DL 720                                                                                                                                                           
        - TVripHD 720                                                                                                                                                          
    imdb_lookup: yes                                                                                                                                                           
    duplicates:                                                                                                                                                                
      field: imdb_id                                                                                                                                                           
      action: reject                                                                                                                                                           
    rtorrent:                                                                                                                                                                  
      uri: scgi://localhost:58519                                                                                                                                              
      path: /home/pastadmin/torrents/rtorrent/                                                                                                                                 
      custom1: flexget                                                                                                                                            

web_server:                                                                                                                                                                    
  bind: 0.0.0.0 # IP V4                                                                                                                                                        
  port: 3539 # Valid port number                                                                                                                                               
  ssl_certificate: '/etc/ssl/private/myCert.pem' # Path to certificate file                                                                                                   
  ssl_private_key: '/etc/ssl/private/myKey.key' # Path to private key file                                                                                                    
  web_ui: yes # Web-UI can optionally be disabeled, only API will run 
EOF
echo ""
flexget t411 add-auth $t411usr $t411pwd 
flexget web passwd $flexgetwebuipwd
flexget daemon start -d
echo ""
echo "Flexget is installed !"
echo ""
