#!/usr/bin/env bash       
clear
externalip=$(curl -s ident.me)                            
RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[1;32m'
NC='\033[0m' # No Color                                                                                                                          
spinner() {                                                                                                                                                                    
    local i sp n                                                                                                                                                               
    sp='/-\|'                                                                                                                                                                  
    n=${#sp}                                                                                                                                                                   
    printf ' '                                                                                                                                                                 
    while sleep 0.1; do                                                                                                                                                        
        printf "%s\b" "${sp:i++%n:1}"                                                                                                                                          
    done                                                                                                                                                                       
}
echo 
echo "Welcome to Koel installer for Quickbox.io !"
echo "For more information, you could check the Koel's website : http://koel.phanan.net/" 
echo "The installation may during up to 10 minutes!"
echo 

printf "${YELLOW}Setting up environnement ...${NC}"                                                                                                            
spinner &                                                                                                                                                                      
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -  
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list  
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -                                                                                                                                                                            
kill "$!"
wait "$!" 2>/dev/null
printf "${GREEN}Done.${NC}\n"

printf "${YELLOW}Installing dependencies ...${NC}"                                                                                                            
spinner & 
apt-get update 
apt-get install -y apache2 php g++ git curl mariadb-server php-curl php-mysql php-mbstring phpunit nodejs yarn unzip libnotify-bin 
kill "$!" 
wait "$!" 2>/dev/null 
printf "${GREEN}Done.${NC}\n" 

printf "${YELLOW}Cloning Koel ...${NC}"                                                                                                            
spinner & 
git clone https://github.com/phanan/koel.git /srv/koel  
kill "$!" 
wait "$!" 2>/dev/null 
printf "${GREEN}Done.${NC}\n" 

printf "${YELLOW}Installing Composer and setting MySQL configuration ...${NC}"                                                                                                            
spinner & 
cd /srv/koel/                                                                                                                                                       
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/srv/koel --filename=composer  
sed -i "/BROADCAST_DRIVER/c 	'default' => env('BROADCAST_DRIVER', 'log')," config/broadcasting.php
mysql --user="root" --password="$password" --execute="CREATE DATABASE koeldb DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"
mysql --user="root" --password="$password" --execute="CREATE USER 'koelusr'@'localhost' IDENTIFIED BY 'koelpwd';"
mysql --user="root" --password="$password" --execute="GRANT ALL PRIVILEGES ON koeldb.* TO 'koelusr'@'localhost' WITH GRANT OPTION;"
mysql --user="root" --password="$password" --execute="FLUSH PRIVILEGES;"  
kill "$!" 
wait "$!" 2>/dev/null 
printf "${GREEN}Done.${NC}\n" 

printf "${YELLOW}Composing Koel ...${NC}"                                                                                                            
spinner & 
./composer install  
sed -i 's/ADMIN_EMAIL=/ADMIN_EMAIL=johndoe@gmail.com/g' .env
sed -i 's/ADMIN_NAME=/ADMIN_NAME=JohnDoe/g' .env
sed -i 's/ADMIN_PASSWORD=/ADMIN_PASSWORD=koelpwd/g' .env
sed -i 's/DB_CONNECTION=/DB_CONNECTION=mysql/g' .env
sed -i 's/DB_HOST=/DB_HOST=127.0.0.1/g' .env
sed -i 's/DB_DATABASE=/DB_DATABASE=koeldb/g' .env
sed -i 's/DB_USERNAME=/DB_USERNAME=koelusr/g' .env
sed -i 's/DB_PASSWORD=/DB_PASSWORD=koelpwd/g' .env  
kill "$!" 
wait "$!" 2>/dev/null 
printf "${GREEN}Done.${NC}\n" 

printf "${YELLOW}Initializating Koel ...${NC}"                                                                                                            
spinner & 
php artisan koel:init  
kill "$!" 
wait "$!" 2>/dev/null 
printf "${GREEN}Done.${NC}\n" 

printf "${YELLOW}Configuring Koel modules ...${NC}"                                                                                                            
spinner & 
yarn  
cd node_modules/.bin/ 
npm install --save-dev node-sass  
./gulp 
kill "$!" 
wait "$!" 2>/dev/null 
printf "${GREEN}Done.${NC}\n" 

printf "${YELLOW}Starting Koel ...${NC}"                                                                                                            
spinner & 
cd /srv/koel                 
screen -S koel -dm php artisan serve --host 0.0.0.0
kill "$!" 
wait "$!" 2>/dev/null 
printf "${GREEN}Done.${NC}\n" 

echo ""
echo "Koel is installed ! \o/"
echo "Koel is accessible at http://$externalip:8000"
echo "Reverse proxy is coming ;)"
echo ""


