#!/bin/bash
#
# [Quick Box :: Install FreshRSS package]
#
# GITHUB REPOS
# GitHub _ packages  :   https://github.com/QuickBox/quickbox_packages
# LOCAL REPOS
# Local _ packages   :   ~/QuickBox/packages
# Author             :   PastaGringo
# URL                :   https://plaza.quickbox.io
#
# QuickBox Copyright (C) 2016 QuickBox.io
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.

inst=$(which mysql)
ip=$(ip route get 8.8.8.8 | awk 'NR==1 {print $NF}')

echo "Please choose a password for the FreshRSS mysql user."
read -s -p "Password: " 'freshpass'
#Check for existing mysql and install if not found
if [[ -n $inst ]]; then
  echo -n -e "Existing mysql server detected!\n"
  echo -n -e "Please enter mysql root password so that installation may continue:\n"
  read -s -p "Password: " 'password'
  echo -e "Please wait while FreshRSS is installed ... "

else
  echo -n -e "No mysql server found! Setup will install. \n"
  echo -n -e "Please enter a mysql root password \n"
  while [ -z "$password" ]; do
    read -s -p "Password: " 'pass1'
    echo
    read -s -p "Re-enter password to verify: " 'pass2'
    if [ $pass1 = $pass2 ]; then
       password=$pass1
    else
       echo
       echo "Passwords do not match"
    fi
  done
  echo -e "Please wait while FreshRSS is installed ... "
  sudo apt-get -y install mariadb-server 
  mysqladmin -u root password ${password}
fi

echo -e "Installing dependencies ..."
# If you use an Apache Web server (otherwise you need another Web server)
sudo a2enmod headers expires rewrite ssl    #Apache modules

# For Ubuntu >= 16.04, Debian >= 9 Stretch
sudo apt install php php-curl php-gmp php-intl php-mbstring php-sqlite3 php-xml php-zip git -y
sudo apt install libapache2-mod-php -y #For Apache

# Restart Web server
sudo service apache2 restart

# For FreshRSS itself (git is optional if you manually download the installation files)
cd /srv
sudo git clone https://github.com/FreshRSS/FreshRSS.git
cd FreshRSS

# Set the rights so that your Web server can access the files
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
cat > /etc/apache2/sites-enabled/freshrss.conf <<EOF
Alias /freshrss "/srv/FreshRSS/"
<Directory /srv/FreshRSS/>
 Options +FollowSymlinks
 AllowOverride All
 Require all granted
</Directory>
EOF

echo "Creating Database ..."
mysql --user="root" --password="$password" --execute="CREATE DATABASE freshrss;"
mysql --user="root" --password="$password" --execute="CREATE USER freshrss@localhost IDENTIFIED BY '$freshpass';"
mysql --user="root" --password="$password" --execute="GRANT ALL PRIVILEGES ON freshrss.* TO freshrss@localhost;"
mysql --user="root" --password="$password" --execute="FLUSH PRIVILEGES;"

echo "Creating custom menu ..."
wget https://github.com/PastaGringo/scripts/raw/master/freshrss_logo.png -P /srv/rutorrent/home/img/brands
chown www-data:www-data /srv/rutorrent/home/img/brands/freshrss_logo.png
sed -i '/plaza.quickbox.io/a $freshrssURL= "https://" . $_SERVER['HTTP_HOST'] . "/freshrss";' /srv/rutorrent/home/custom/custom.menu.php
sed -i '/QuickBox Plaza/a <li><a class="grayscale" href="<?php echo "$freshrssURL"; ?>" target="_blank"><img src="img/brands/freshrss_logo.png" class="brand-ico"> <span>Fresh RSS</span></a></li>' /srv/rutorrent/home/custom/custom.menu.php
touch /install/.freshrss.lock
service apache2 reload

echo -e "FreshRSS installed!"
echo -e "Visit https://${ip}/freshrss to finish installation."
echo -e "Database user: freshrss"
echo -e "Database password: ${freshpass}"
echo -e "Database name: freshrss"
