#!/usr/bin/env bash       
clear
externalip=$(curl -s ident.me)                            
RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[1;32m'
NC='\033[0m' # No Color                                                                                                                          
spinner() {                                                                                                                                                                    
    local i sp n                                                                                                                                                               
    sp='/-\|'                                                                                                                                                                  
    n=${#sp}                                                                                                                                                                   
    printf ' '                                                                                                                                                                 
    while sleep 0.1; do                                                                                                                                                        
        printf "%s\b" "${sp:i++%n:1}"                                                                                                                                          
    done                                                                                                                                                                       
}
echo 
echo "Welcome to Cardigann installer for Quickbox.io !"
echo "For more information, you could check the Cardigann's website : https://github.com/cardigann/cardigann" 
echo 
printf "${YELLOW}Installing Cardigann ...${NC}"                                                                                                            
spinner &        
cd /opt
mkdir cardigann && cd cardigann
wget https://bin.equinox.io/c/3u8U4iwUn6o/cardigann-stable-linux-amd64.tgz     
tar xvzf cardigann-stable-linux-amd64.tgz                                                                                                          
rm -rf cardigann-stable-linux-amd64.tgz     
./cardigann service install
service Cardigann start                                                                                                                                                       
kill "$!"
wait "$!" 2>/dev/null
printf "${GREEN}Done.${NC}\n"
echo
echo -e "Cardigann installed!"
echo -e "Visit http://$externalip:5060 to use it!"
