#!/bin/bash
sudo apt-get update
sudo apt-get install -y git screen
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
sudo groupadd docker
sudo usermod -aG docker $USER
sudo curl -O https://dl.google.com/go/go1.11.1.linux-amd64.tar.gz
sudo tar -xvf go1.11.1.linux-amd64.tar.gz
sudo mv go /usr/local
echo 'export PATH=$PATH:/usr/local/go/bin" >> ~/.profile'
source ~/.profile
go version
go get gitlab.com/ahmida/pushrocket/pushrocket
go build gitlab.com/ahmida/pushrocket/pushrocket
go install gitlab.com/ahmida/pushrocket/pushrocket
go get gitlab.com/ahmida/pushrocket/pullrocket
go build gitlab.com/ahmida/pushrocket/pullrocket
go install gitlab.com/ahmida/pushrocket/pullrocket
sudo docker pull eclipse-mosquitto
sudo docker run -d -it -p 1883:1883 -p 9001:9001 eclipse-mosquitto
pushrocket config --address "tcp://localhost:1883"
pairstring=$(pushrocket pair)
pairstring2="'$pairstring'"
pullrocket pair $pairstring2
screen -dmS pullrocket
screen -x pullrocket pullrocket pull
