#!/bin/bash
cd /tmp
echo   __  __           _            _                   _     
echo |  \/  | __ _ ___| |_ ___   __| | ___  _ __    ___| |__  
echo | |\/| |/ _` / __| __/ _ \ / _` |/ _ \| '_ \  / __| '_ \ 
echo | |  | | (_| \__ \ || (_) | (_| | (_) | | | |_\__ \ | | |
echo |_|  |_|\__,_|___/\__\___/ \__,_|\___/|_| |_(_)___/_| |_|
echo
echo "Welcome to Mastodon.sh !"
echo "This script has been created by PastaGringo with indirect help of Angristan"
echo
echo "This script works on Debian 8 (Jessie) and is still in development"
echo
echo "There are few things that you need to know before continuing if you want your own fonctionnal Mastodon instance :"
echo "- You need to have a valid domain name with an A DNS record with the local server IP address"
echo "- You need to have an account with a SMTP tiers like Mailgun/SparkPost or you own SMTP relay"
echo "- Few dozen of minutes regarding of your server performances"
echo
echo "If all above things are in your possession, we can continue and install your first Mastodon instance !"
echo
pause
clear
echo
echo "This script allow to configure a Mailgun account, in order to send mail activation for new Mastodon's users."
echo "If you don't use Mailgun (or other services), you will need to modify the SMTP settings in the file "/home/mastodon/live/.env.production""
echo "Do you want to configure your Mailgun account ? [y/n]"
                                                          

                                                          
