#!/bin/bash
cd /tmp
echo
echo "Hello, welcome the Mastodon auto-intaller !"
echo "Could please give me your domain name? ONLY in this format >> domain.tld <<"
read domainwithtld
domain=$(echo $domainwithtld | cut -d'.' -f 1) 
echo
echo "One last thing... could you give your email accout ? (for letsencrypt certificate) : "
read email  
echo 
echo GO
rubyversion=$(curl -s https://raw.githubusercontent.com/tootsuite/mastodon/master/.ruby-version)    
echo "Mastodon Ruby version is : " $rubyversion
echo
echo "deb http://httpredir.debian.org/debian jessie-backports main" >> /etc/apt/sources.list
apt update && apt full-upgrade -y
apt-get install imagemagick ffmpeg libpq-dev libxml2-dev libxslt1-dev file curl git -y
echo
echo NODEJS 
echo
curl -sL https://deb.nodesource.com/setup_4.x | bash -
apt install nodejs -y
npm install -g yarn 
apt install redis-server redis-tools -y
echo
echo POSTGRES  
echo
apt-get install postgresql postgresql-contrib -y
su - postgres -c "psql -c 'CREATE USER mastodon CREATEDB;'"  
adduser --disabled-password --disabled-login --gecos "" mastodon
echo "mastodon ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
apt install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev -y
su - mastodon << EOF
git clone https://github.com/rbenv/rbenv.git /home/mastodon/.rbenv
cd /home/mastodon/.rbenv && src/configure && make -C src
echo 'export PATH="/home/mastodon/.rbenv/bin:$PATH"' >> /home/mastodon/.bash_profile
EOF
echo 'eval "$(rbenv init -)"' >> /home/mastodon/.bash_profile
su - mastodon << EOF
git clone https://github.com/rbenv/ruby-build.git /home/mastodon/.rbenv/plugins/ruby-build
rbenv install --verbose $rubyversion
rbenv global $rubyversion
gem install bundler
cd /home/mastodon
git clone https://github.com/tootsuite/mastodon.git live
cd live
bundle install --deployment --without development test
yarn install
cp .env.production.sample .env.production
EOF
echo
echo switch 1
echo
cd /home/mastodon/live
secret1=$(/home/mastodon/.rbenv/shims/bundle exec rake secret)
secret2=$(/home/mastodon/.rbenv/shims/bundle exec rake secret)
secret3=$(/home/mastodon/.rbenv/shims/bundle exec rake secret)
export secret1 secret2 secret3
echo
echo switch 2
echo
su - mastodon << EOF
cd /home/mastodon/live
sed -i '/REDIS_HOST/c\REDIS_HOST=localhost' .env.production
sed -i '/DB_HOST/c\DB_HOST=/var/run/postgresql' .env.production
sed -i '/DB_USER/c\DB_USER=mastodon' .env.production
sed -i '/DB_NAME/c\DB_NAME=mastodon_production' .env.production
sed -i '/LOCAL_DOMAIN/c\LOCAL_DOMAIN=${domainwithtld}' .env.production
sed -i 's/PAPERCLIP_SECRET=/PAPERCLIP_SECRET=${secret1)/g' .env.production
sed -i 's/SECRET_KEY_BASE=/SECRET_KEY_BASE=${secret2)/g' .env.production
sed -i 's/OTP_SECRET=/OTP_SECRET=${secret3)/g' .env.production
EOF
