#!/bin/bash
# Ask the user for their name
echo
echo "Hello, welcome the Mastodon auto-intaller !"
echo "Could please give me your domain name? (ONLY in this format >> www.domain.tld) : "
read fqdn

www=$(echo $fqdn | cut -d'.' -f 1) 
domain=$(echo $fqdn | cut -d'.' -f 2) 
tld=$(echo $fqdn | cut -d'.' -f 3) 

echo $www
echo $domain
echo $tld


echo "One last thing... could you give your email accout ? (for letsencrypt certificate) : "
read email 

echo $email
