#!/bin/bash
cd /tmp
echo
echo "Hello, welcome the Mastodon auto-intaller !"
echo "Could please give me your domain name? ONLY in this format >> domain.tld <<"
read domainwithtld
domain=$(echo $domainwithtld | cut -d'.' -f 1) 
echo
rm .env.production
cp .env.production.sample .env.production
sed -i '/REDIS_HOST/c\REDIS_HOST=localhost' .env.production
sed -i '/DB_HOST/c\DB_HOST=/var/run/postgresql' .env.production
sed -i '/DB_USER/c\DB_USER=mastodon' .env.production
sed -i '/DB_NAME/c\DB_NAME=mastodon_production' .env.production
sed -i '/LOCAL_DOMAIN/c\LOCAL_DOMAIN=domainedevotreinstance.tld' .env.production
sed -i '/PAPERCLIP_SECRET/c\PAPERCLIP_SECRET='$(bundle exec rake secret)'' .env.production
sed -i '/SECRET_KEY_BASE/c\SECRET_KEY_BASE='$(bundle exec rake secret)'' .env.production
sed -i '/OTP_SECRET/c\OTP_SECRET='$(bundle exec rake secret)'' .env.production
