#!/bin/bash
# FreshRSS uninstaller
echo -n -e "Please enter mysql root password so that FreshRSS database and user can be dropped.\n"
read -s -p "Password: " 'password'
rm -rf /srv/FreshRSS /srv/rutorrent/home/img/brands/freshrss_logo.png /etc/apache2/sites-enabled/freshrss.conf /install/.freshrss.lock
sed -i '/freshrssURL/d' /srv/rutorrent/home/custom/custom.menu.php                                                                                               
mysql --user="root" --password="$password" --execute="DROP DATABASE freshrss;"
mysql --user="root" --password="$password" --execute="DROP USER freshrss@localhost;"
service apache2 reload
echo "FreshRSS uninstalled !"
