#!/bin/bash
echo "Laraval env installer"
echo "Please wait ..."
echo
#INSTALL DEPENDENCIES
apt-get install -y apache2 php git curl unzip php-mbstring php-xml phpunit php7.0-mysql mariadb-server libapache2-mod-php
#INSTALL COMPOSER
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '61069fe8c6436a4468d0371454cf38a812e451a14ab1691543f25a9627b97ff96d8753d92a00654c21e2212a5ae1ff36') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar /usr/local/bin/composer
#MySQL
mysql --user="root" --password="$password" --execute="CREATE DATABASE homestead DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"
mysql --user="root" --password="$password" --execute="CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret';"
mysql --user="root" --password="$password" --execute="GRANT ALL PRIVILEGES ON homestead.* TO 'homestead'@'localhost' WITH GRANT OPTION;"
mysql --user="root" --password="$password" --execute="FLUSH PRIVILEGES;"  
#CANVAS
composer create-project --prefer-dist cnvs/canvas blog
php artisan key:generate

