#!/usr/bin/env bash
spinner() {
    local i sp n
    sp='/-\|'
    n=${#sp}
    printf ' '
    while sleep 0.1; do
        printf "%s\b" "${sp:i++%n:1}"
    done
}
printf 'working'
spinner &
$cmd
kill "$!" # kill the spinner
printf '\n'

cmd=apt-get update && apt-get install -y apache2 php g++ git curl mariadb-server php-curl php-mysql php-mbstring phpunit unzip
spinner
